### ISSUE TITLE
Landscape mode ?

### ISSUE THREAD

**Issue by ghost** [MaskyS/Studento#2]
its more work to make it work in Landscape mode i know.

But my kids use tablets and chromebooks so it woudl be way easier in Landscape mode.

**Comment by MaskyS** [comment]
Thanks for opening an issue @gedw99 :)  Currently I've disabled landscape mode as it breaks a few UI components(namely, the layout of the buttons on the homepage). This app is a WIP,  but once I get the basic functionality right, I promise to work on this. If you have any advice on how we can proceed, let us know. (or even better, send a PR) :smile:

**Comment by ghost** [comment]
I wish.. No time...

Regarding layout. Yeah its tricky and there are classes in Flutter
specifically for it.
But i would do a bit of research on github to find a helper library maybe..
There might be one and its the sort of thing that would help alot of
suspect.

If i happen to come across one i will def let you know
